### ISSUE TITLE
Input box sizes

### ISSUE THREAD

**Issue by Manjula85** [Manjula85/HTML-CSS-Project-2#1]
Can I make all the input box sizes (i.e. name, email and age) the same size?

**Comment by dnguneratne** [comment]
Since this is in a table you can set width for td > input. 

Something like,
```html
<td>
  <input type="text" id="name" name="name" placeholder="Enter your name" style="width: 50%">
</td>
```

**Comment by Manjula85** [comment]
> Since this is in a table you can set width for td > input.
> 
> Something like,
> 
> ```
> <td>
>   <input type="text" id="name" name="name" placeholder="Enter your name" style="width: 50%">
> </td>
> ```

Yeah, that worked. Thanks!
